Refactoring, changed aliases name

diff --git a/bash-extensions b/bash-extensions
--- a/bash-extensions
+++ b/bash-extensions
@@ -78,6 +78,7 @@ lsvn (){
 # |  _|| |_| | | | | (__| |_| | (_) | | | \__ \
 # |_|   \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 #
+###############################################
 
 #Remove prompt command
 cleanprompt() {
@@ -96,11 +97,41 @@ function cd() {
     builtin cd "${destination}" >/dev/null && ls
 }
 
+# # ex - archive extractor
+# # usage: ex <file>
+ex ()
+{
+  if [ -f $1 ] ; then
+    case $1 in
+      *.tar.bz2)   tar xvjf $1   ;;
+      *.tar.gz)    
+          tar xvzf $1   
+          if [ $? -ne 0 ]; then
+              tar xvf $1
+          fi    ;;
+      *.bz2)       bunzip2 $1   ;;
+      *.rar)       unrar x $1     ;;
+      *.gz)        gunzip $1    ;;
+      *.tar)       tar xvf $1    ;;
+      *.tbz2)      tar xvjf $1   ;;
+      *.tgz)       tar xvzf $1   ;;
+      *.zip)       unzip $1     ;;
+      *.Z)         uncompress $1;;
+      *.7z)        7z x $1      ;;
+      *)           echo "'$1' cannot be extracted via ex()" ;;
+    esac
+  else
+    echo "'$1' is not a valid file"
+  fi
+}
+
 #    _              _ _     _      
 #   / \   _ __  ___(_) |__ | | ___ 
 #  / _ \ | '_ \/ __| | '_ \| |/ _ \
 # / ___ \| | | \__ \ | |_) | |  __/
 #/_/   \_\_| |_|___/_|_.__/|_|\___|
+#
+###################################
 
 arole (){
     if [ "$#" -lt 1 ]; then
@@ -174,6 +205,5 @@ notepad() {
             ;;
     esac
 }
-#============== NOTEPAD END =================
 
 
